@startuml cms-ev-battery-health-runtime-user-sequence-diagram
'Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
'SPDX-License-Identifier: MIT (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/master/LICENSE)

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/Storage/SimpleStorageService.puml
!include AWSPuml/ManagementGovernance/ManagedGrafana.puml
!include AWSPuml/SecurityIdentityCompliance/IAMIdentityCenter.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/ApplicationIntegration/SimpleNotificationServiceTopic.puml
!include AWSPuml/Analytics/Athena.puml
!include AWSPuml/Analytics/Glue.puml
!include AWSPuml/ApplicationIntegration/AppSync.puml
!include AWSPuml/SecurityIdentityCompliance/Cognito.puml

!define GREEN #3F8624
!define YELLOW #D86613
!define RED #E3242B
!define PINK #CF2465
!define PURPLE #8b27f5

'Comment out to use default PlantUML sequence formatting
skinparam participant {
    BackgroundColor AWS_BG_COLOR
    BorderColor AWS_BORDER_COLOR
}
skinparam sequence {
    ArrowThickness 2
    LifeLineBorderColor AWS_COLOR
    LifeLineBackgroundColor AWS_BORDER_COLOR
    BoxBorderColor AWS_COLOR
}

actor User as user
box CMS EV Battery Health Module Runtime - User Workflow
participant "$IAMIdentityCenterIMG()\nIAM Identity\n Center" as iam << IAM Identity Center >>
participant "$ManagedGrafanaIMG()\nGrafana" as grafana << Grafana >>
participant "$AthenaIMG()\nAthena" as athena << Athena >>
participant "$GlueIMG()\nGlue" as glue << Glue >>
participant "$SimpleStorageServiceIMG()\nVSS S3" as vss_s3 << S3 >>
participant "$SimpleNotificationServiceTopicIMG()\nSNS Topic" as sns << SNS >>
participant "$LambdaIMG()\nProcess Alerts" as process_alerts << Lambda >>
participant "$CognitoIMG()\nCognito\n User Pool" as cognito <<Cognito>>
participant "$AppSyncIMG()\nAlerts API" as api <<AppSync>>

endbox

user -> grafana++ PINK: Navigate to Grafana workspace
grafana -> iam++ RED: Redirect to IAM Identity Center Login page
user -> iam: Login using user credentials
grafana <-- iam
deactivate iam
user <-- grafana: Redirect to Grafana workspace homepage
deactivate grafana

|||

user -> grafana++ PINK: Open EV Battery Health dashboard
grafana -> athena++ PURPLE: Query Athena for the dashboard panel data
athena -> glue++ PURPLE: Query Glue catalog, database and table for VSS data
glue -> vss_s3++ GREEN: Get VSS data from storage bucket
glue <-- vss_s3
deactivate vss_s3
athena <-- glue
deactivate glue
grafana <-- athena
deactivate athena
user <-- grafana
deactivate grafana

|||

user -> grafana++ PINK
grafana -> grafana: Check alert rules periodically
grafana -> athena++ PURPLE: Query Athena for the alert rule data
athena -> glue++ PURPLE: Query Glue catalog, database and table for VSS data
glue -> vss_s3++ GREEN: Get VSS data from storage bucket
glue <-- vss_s3
deactivate vss_s3
athena <-- glue
deactivate glue
grafana <-- athena
deactivate athena
grafana -> sns++ PINK: If alert rule is breached, send alert payload to SNS topic
sns -> process_alerts++ YELLOW: Process SNS alert payload and convert it to a custom format
process_alerts -> cognito++ RED: Get access token using service client credentials
process_alerts <-- cognito
deactivate cognito
process_alerts -> api++ PINK: Publish alert payload to Alerts endpoint
process_alerts <-- api
deactivate api
sns <-- process_alerts
deactivate process_alerts
grafana <-- sns
deactivate sns
user <-- grafana
deactivate grafana

@enduml
