version: 0.2

phases:
  build:
    commands:
      # Build and deploy
      - |
        aws cloudformation create-stack \
        --stack-name "${MODULE_STACK_NAME}" \
        --template-url "${CFN_TEMPLATE_URL}" \
        --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
        --role-arn "${CLOUDFORMATION_ROLE_ARN}" \
        --parameters \
        ParameterKey="UserEmail",ParameterValue="${USER_EMAIL}" \
        ParameterKey="AppUniqueId",ParameterValue="${APP_UNIQUE_ID}"
