# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

exclude: '^.*\.svg$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-executables-have-shebangs
        name: (ROOT) Check executables have shebangs
        exclude: ^(source/|.nightswatch/)
      - id: fix-byte-order-marker
        name: (ROOT) Fix byte order marker
        exclude: ^(source/|.nightswatch/)
      - id: check-case-conflict
        name: (ROOT) Check case conflict
        exclude: ^(source/|.nightswatch/)
      - id: check-json
        name: (ROOT) Check json
        exclude: ^(source/|.nightswatch/)
      - id: check-yaml
        name: (ROOT) Check yaml
        exclude: ^(source/|.nightswatch/)
        args: [--allow-multiple-documents, --unsafe]
      - id: check-toml
        name: (ROOT) Check toml
        exclude: ^(source/|.nightswatch/)
      - id: check-merge-conflict
        name: (ROOT) Check for merge conflicts
        exclude: ^(source/|.nightswatch/)
      - id: check-added-large-files
        name: (ROOT) Check for added large files
        exclude: |
          (?x)^(
            ^source/ |
            ^.nightswatch/ |
            ^.*/package-lock.json |
            ^.*/yarn.lock |
            ^.*/Pipfile.lock
          )$
      - id: end-of-file-fixer
        name: (ROOT) Fix end of the files
        exclude: ^(source/|.nightswatch/)
      - id: fix-encoding-pragma
        name: (ROOT) Fix python encoding pragma
        exclude: ^(source/|.nightswatch/)
      - id: trailing-whitespace
        name: (ROOT) Trim trailing whitespace
        exclude: ^(source/|.nightswatch/)
      - id: mixed-line-ending
        name: (ROOT) Mixed line ending
        exclude: ^(source/|.nightswatch/)
      - id: detect-aws-credentials
        name: (ROOT) Detect AWS credentials
        exclude: ^(source/|.nightswatch/|buildspec.yml)
        args: ["--credentials-file", "~/.ada/credentials"]
      - id: detect-private-key
        name: (ROOT) Detect private keys
        exclude: ^(source/|.nightswatch/)
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: insert-license
        name: (ROOT) Insert license header (python)
        exclude: ^(source/|.nightswatch/)
        files: \.py$
        args:
          - --license-filepath
          - ./license_header.txt
          - --detect-license-in-X-top-lines=3
      - id: insert-license
        name: (ROOT) Insert license header (typescript and javascript)
        files: \.tsx$|\.ts$|\.js$|\.jsx$
        exclude: ^(source/|.nightswatch/)
        args:
          - --license-filepath
          - ./license_header.txt
          - --comment-style
          - // # defaults to Python's # syntax, requires changing for typescript syntax.
          - --detect-license-in-X-top-lines=3
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        name: (ROOT) Black
        exclude: ^(source/|.nightswatch/)
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln
        name: (ROOT) Pycln
        exclude: ^(source/|.nightswatch/)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: (ROOT) Isort (python)
        exclude: ^(source/|.nightswatch/)
        args: ["--skip-glob", "**/node_modules/* **/.venv/*", "--settings-path", "./pyproject.toml"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: (ROOT) Bandit
        exclude: ^(source/|.nightswatch/)
        args: ["-c", "./pyproject.toml"]
        additional_dependencies: [ "bandit[toml]" ]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.6.1
    hooks:
      - id: pip-audit
        name: (ROOT) Pip audit
        exclude: ^(source/|.nightswatch/)
  - repo: https://github.com/pre-commit/mirrors-prettier # Archived, look to replace eventually
    rev: v3.1.0
    hooks:
      - id: prettier
        name: (ROOT) Prettier
        types_or: [javascript, jsx, ts, tsx]
        exclude: ^(source/|.nightswatch/)
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        name: (ROOT) MarkdownLint
        exclude: ^(source/|.nightswatch/)
  # Local
  - repo: local
    hooks:
      - id: detect-empty-files
        name: (ROOT) detect-empty-files
        exclude: ^(source/|.nightswatch/)
        entry: deployment/run-detect-empty-files.sh
        language: system
        pass_filenames: false
      - id: shellcheck
        name: (ROOT) Shellchecker
        exclude: ^(source/|.nightswatch/)
        entry: ./deployment/run-shellcheck.sh
        args: ["-x"]
        types: [shell]
        language: system
      - id: pylint
        name: (ROOT) pylint
        exclude: ^(source/|.nightswatch/)
        entry: pipenv run pylint
        args: ["--extension-pkg-allow-list", "math", "--rcfile", "./pyproject.toml"]
        types: [python]
        language: system
        require_serial: true
      - id: mypy
        name: (ROOT) mypy
        exclude: ^(source/|.nightswatch/)
        entry: pipenv run mypy
        types_or: [python, pyi]
        args: ["--strict", "--cache-dir", "./.mypy_cache", "--config-file", "./pyproject.toml"]
        language: system
        require_serial: true
  # Module pre-commits: https://github.com/pre-commit/pre-commit/issues/731#issuecomment-376945745
  - repo: local
    hooks:
      - id: acdp
        name: (ACDP)
        language: script
        args: ["--module-path", "source/modules/acdp", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/acdp
        verbose: true
        require_serial: true
      - id: backstage
        name: (Backstage)
        language: script
        args: ["--module-path", "source/modules/backstage", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/backstage
        verbose: true
        require_serial: true
      - id: cms-alerts
        name: (Alerts)
        language: script
        args: ["--module-path", "source/modules/cms_alerts", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_alerts
        verbose: true
        require_serial: true
      - id: cms-api
        name: (API)
        language: script
        args: ["--module-path", "source/modules/cms_api", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_api
        verbose: true
        require_serial: true
      - id: cms_common
        name: (Common)
        language: script
        args: ["--module-path", "source/lib", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/lib
        verbose: true
        require_serial: true
      - id: cms-config
        name: (Config)
        language: script
        args: ["--module-path", "source/modules/cms_config", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_config
        verbose: true
        require_serial: true
      - id: cms-connect-store
        name: (Connect Store)
        language: script
        args: ["--module-path", "source/modules/cms_connect_store", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_connect_store
        verbose: true
        require_serial: true
      - id: cms-ev-battery-health
        name: (EV Battery Health)
        language: script
        args: ["--module-path", "source/modules/cms_ev_battery_health", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_ev_battery_health
        verbose: true
        require_serial: true
      - id: cms-provisioning
        name: (Provisioning)
        language: script
        args: ["--module-path", "source/modules/cms_provisioning", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_provisioning
        verbose: true
        require_serial: true
      - id: cms-sample
        name: (Sample)
        language: script
        args: ["--module-path", "source/modules/cms_sample", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_sample
        verbose: true
        require_serial: true
      - id: cms-auth
        name: (Auth)
        language: script
        args: ["--module-path", "source/modules/cms_auth", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_auth
        verbose: true
        require_serial: true
      - id: cms-vehicle-simulator
        name: (Vehicle Simulator)
        language: script
        args: ["--module-path", "source/modules/cms_vehicle_simulator", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_vehicle_simulator
        verbose: true
        require_serial: true
      - id: cms-fleetwise-connector
        name: (FleetWise Connector)
        language: script
        args: ["--module-path", "source/modules/cms_fleetwise_connector", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_fleetwise_connector
        verbose: true
        require_serial: true
      - id: auth-setup
        name: (Auth Setup)
        language: script
        args: ["--module-path", "source/modules/auth_setup", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/auth_setup
        verbose: true
        require_serial: true
      - id: vpc
        name: (VPC)
        language: script
        args: ["--module-path", "source/modules/vpc", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/vpc
        verbose: true
        require_serial: true
      - id: cms-predictive-maintenance
        name: (Predictive Maintenance)
        language: script
        args: ["--module-path", "source/modules/cms_predictive_maintenance", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_predictive_maintenance
        verbose: true
        require_serial: true
      - id: nightswatch
        name: (NightsWatch)
        language: script
        args: ["--module-path", ".nightswatch", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^.nightswatch
        verbose: true
        require_serial: true
      - id: cms-ui
        name: (UI)
        language: script
        args: ["--module-path", "source/modules/cms_ui", "--files-list"]
        entry: ./deployment/script_run_module_hooks.py
        files: ^source/modules/cms_ui
        verbose: true
        require_serial: true
