@startuml acdp-github-cicd-sequence-diagram
'Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
'SPDX-License-Identifier: MIT (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/master/LICENSE)

!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/sprites
!includeurl SPRITESURL/github-icon.puml
!includeurl SPRITESURL/github-actions.puml
!includeurl SPRITESURL/spotify-icon.puml

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v13.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/DeveloperTools/CodeBuild.puml
!include AWSPuml/Storage/SimpleStorageService.puml
!include AWSPuml/ManagementGovernance/CloudFormation.puml
!include AWSPuml/Containers/ElasticContainerRegistry.puml
!include AWSPuml/ManagementGovernance/Proton.puml

sprite $backstage-icon [50x50/16] {
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEDDEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEFEDFFDEFEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEFEEF8AFEDFEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEFEDF7237FFDEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEFEEF7233249FFDEFEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEFEEF623323336CFEDFEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEFEEF623236323237FFDEFEEEEEEEEEE
EEEEEEEEEEEEEEEEEEFEEF623239FB523324AFFDFEEEEEEEEE
EEEEEEEEEEEEEEEEEFDFF62323AFDFF9423236DFDEEEEEEEEE
EEEEEEEEEEEEEEEEFDFF52323AFDEDEFF632323AFDFEEEEEEE
EEEEEEEEEEEEEEEFDFF52323BFDFEEEDFFB52323AFDFEEEEEE
EEEEEEEEEEEEEEFDFF52334BFDFEEEEFEDFF62324FFEEEEEEE
EEEEEEEEEEEEEFDFF423339FDDEFEEEEEFDFF42328FDFEEEEE
EEEEEEEEEEEEFDFD42323336EFEDFEEEEEFDF62326FDEEEEEE
EEEEEEEEEEEFDFD42324323248FFDEFEEFEDF52327FDEEEEEE
EEEEEEEEEEFDFC42324FC523325AFFDEEDDF933339FDFEEEEE
EEEEEEEEEFDFB42325FFFF9423236EFFFFF833325FDEEEEEEE
EEEEEEEEFDFB32325FFDEEFF7323246887433324EBEFEEEEEE
EEEEEEEFDFA32325FFEFEEDEFB5333222223225F76FDEEEEEE
EEEEEEEDFA32325FFEFEEEFEDFF83333333349F73AFDFEEEEE
EEEEEEEF933336FDDFEEEEEEFDDF933389ACF9426FDFEEEEEE
EEEEEEEF523335BFFDEFEEEEEFEDF5225F754225FAFFEEEEEE
EEEEEEFDF8333337FFDEFEEEEEEDF6233C42226F66FDEEEEEE
EEEEFEFA5CF6333349FFDEEEEEEFF4233D536AF63BFDFEEEEE
EEEEFEFA337FA433336CFFEEEEFF63334FCDD8426FDFEEEEEE
EEEEEEFD63349F8434347DFFFFD633338F743225F9FEEEEEEE
EEEEEEFDFA5336CD6334346776433336FF42337F57FDEEEEEE
EEEEFEFA5AF74348FA5343333334336F7C647CF53CFDFEEEEE
EEEEEEFB447EC6435AF8544444345AF55FDEB7428FDFEEEEEE
EEEEEEEE74459F95446BFA87778BFA539F744337F9FEEEEEEE
EEEEEEFDFB6446BF744468ABCBA85437FE53348F57FDFEEEEE
EEEEEEFB59F95447FC6444444444448F7C768EC54DFEEEEEEE
EEEEEEFB557CE75459FA654444457BF56FDDA7439FDFEEEEEE
EEEEEEEF95558FB6556AFC9888ACF954BF754448FEFEEEEEEE
EEEEEEFCDD7556AF9555689BBA975449FD64459FEEEEEEEEEE
EEEEEEFB69FA6557DE755555555545AF7C879EFEEEEEEEEEEE
EEEEEEFC657BF96569FB865555568DD67FFFFFDEEEEEEEEEEE
EEEEEEEFA7668ED7656AEEBA9ABED855CFEEDEEEEEEEEEEEEE
EEEEEEEEFD8666AFA756689AAA97655AECFEEEEEEEEEEEEEEE
EEEEEEEEDFFB8667BF966666665556BD7CFEEEEEEEEEEEEEEE
EEEEEEEEFEEFFA7669ED976666679FC68FEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEFD96679CFCBBBDFC866DFEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEFFB8667899A997666BFEFEEEEEEEEEEEEEEE
EEEEEEEEEEEEEFEEFFA76666666668CFEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEFFD98777778AFFEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEFFFDCBCDFFFEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEFFFFFEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
}

'Comment out to use default PlantUML sequence formatting
skinparam participant {
    BackgroundColor AWS_BG_COLOR
    BorderColor AWS_BORDER_COLOR
}
skinparam sequence {
    ArrowThickness 2
    LifeLineBorderColor AWS_COLOR
    LifeLineBackgroundColor AWS_BORDER_COLOR
    BoxBorderColor AWS_COLOR
}

actor User as user

box ACDP Configuration and CI/CD
participant "<$backstage-icon>\nGitHub" as sb << Spotify Backstage >>
participant "<$github-actions>\nGitHub" as gha << GitHub Actions >>
participant "$CodeBuildIMG()\nBackstage PipelineProjects" as bcb << CodeBuild >>
participant "<$github-icon>\nGitHub" as gh << GitHub >>
participant "$CloudFormationIMG()\nCloudFormation" as cfn << CloudFormation >>
participant "$SimpleStorageServiceIMG()\nCloudFormation\nTemplate Bucket" as s3 << S3 Asset >>
endbox

'ACDP Deployment
user -> sb++ #CC2264: Launch Backstage template
sb -> gh++ #3F8624: Create repo
return
sb -> gha++ #D86613: Create GitHub actions from template
gha -> bcb++ #F68D05: Trigger test
bcb -> gh++ #3F8624: Fetch repo
return
return
gha -> bcb++ #F68D05: Trigger build
bcb -> gh++ #3F8624: Fetch repo
return
return
gha -> bcb++ #F68D05: Trigger deploy
bcb -> gh++ #3F8624: Fetch repo
return
bcb -> s3++ #3F8624: Write template
return
bcb -> cfn++ #CC2264: Deploy infrastructure
return
return
return
return

user -> gh #3F8624: Push commit to tracked branch
activate gh #3F8624
user <-- gh
gh -> gha++ #D86613: Actions triggered
gh <-- gha
deactivate gh
gha -> bcb++ #F68D05: Trigger test
bcb -> gh++ #3F8624: Fetch repo
return
return
gha -> bcb++ #F68D05: Trigger build
bcb -> gh++ #3F8624: Fetch repo
return
return
gha -> bcb++ #F68D05: Trigger deploy
bcb -> gh++ #3F8624: Fetch repo
return
bcb -> s3++ #3F8624: Write template
return
bcb -> cfn++ #CC2264: Deploy infrastructure
return
return
@enduml
